//! A library for SuperDARN DMAP file I/O.
//!
//! [![github]](https://github.com/SuperDARNCanada/dmap)&ensp;[![crates-io]](https://crates.io/crates/darn-dmap)&ensp;[![docs-rs]](crate)
//!
//! [github]: https://img.shields.io/badge/github-8da0cb?style=for-the-badge&labelColor=555555&logo=github
//! [crates-io]: https://img.shields.io/badge/crates.io-fc8d62?style=for-the-badge&labelColor=555555&logo=rust
//! [docs-rs]: https://img.shields.io/badge/docs.rs-66c2a5?style=for-the-badge&labelColor=555555&logo=docs.rs
//!
//! <br>
//!
//! This library also has a Python API using pyo3.
//!
//! For more information about DMAP files, see [RST](https://radar-software-toolkit-rst.readthedocs.io/en/latest/)
//! or [pyDARNio](https://pydarnio.readthedocs.io/en/latest/).
//!
//! The main feature of this crate is the [`Record`] trait, which defines a valid DMAP record and functions for
//! reading from and writing to byte streams. The SuperDARN file formats IQDAT, RAWACF, FITACF, GRID, MAP, and SND are
//! all supported with structs that implement [`Record`], namely:
//!
//! - [`IqdatRecord`]
//! - [`RawacfRecord`]
//! - [`FitacfRecord`]
//! - [`GridRecord`]
//! - [`MapRecord`]
//! - [`SndRecord`]
//!
//! Each struct has a list of required and optional fields that it uses to verify the integrity of the record.
//! Only fields listed in the required and optional lists are allowed, no required field can be missing, and
//! each field has an expected primitive type. Additionally, each format has groupings of vector fields which
//! must all share the same shape; e.g. `acfd` and `xcfd` in a RAWACF file.
//!
//! There is also a generic [`DmapRecord`] struct which has no knowledge of required or optional fields. When reading from
//! a byte stream, the parsed data will be identical when using both a specific format like [`RawacfRecord`] and the generic
//! [`DmapRecord`]; however, when writing to a byte stream, the output may differ. Since [`DmapRecord`] has no knowledge of
//! the expected primitive type for each field, it defaults to a type that fits the data. For example, the `stid` field may
//! be saved as an `i8` when using [`DmapRecord`] instead of an `i16` which [`RawacfRecord`] specifies it must be.
//!
//! <div class="note">
//! Each type of record has a specific field ordering hard-coded by this library. This is the order in which fields are written to file,
//! and may not match the ordering of fields generated by RST. This also means that round-trip I/O (i.e. reading a file and
//! writing back out to a new file) is not guaranteed to generate an identical file; however, it is guaranteed that all the
//! information is the same, just not necessarily in the same order.
//! </div>
//!
//! <br>
//!
//! # Examples
//!
//! Convenience functions for reading from and writing to a file exist to simplify the most common use cases.
//! This is defined by [`Record::read_file`]
//! ```
//! use dmap::*;
//! use std::path::PathBuf;
//!
//! # fn main() -> Result<(), DmapError> {
//! let path = PathBuf::from("tests/test_files/test.rawacf");
//! let rawacf_data = RawacfRecord::read_file(&path)?;
//! let unchecked_data = DmapRecord::read_file(&path)?;
//!
//! assert_eq!(rawacf_data.len(), unchecked_data.len());
//! assert_eq!(rawacf_data[0].get(&"stid".to_string()), unchecked_data[0].get(&"stid".to_string()));
//!
//! // Write the records to a file
//! let out_path = PathBuf::from("tests/test_files/output.rawacf");
//! RawacfRecord::write_to_file(&rawacf_data, &out_path, false)?;
//! # std::fs::remove_file(out_path)?;
//! #    Ok(())
//! # }
//! ```
//! You can read from anything that implements the `Read` trait using the functions exposed by the [`Record`] trait.
//! Detection and decompression of bz2 is also conducted automatically.
//! ```
//! use dmap::*;
//! use std::fs::File;
//! use itertools::izip;
//!
//! # fn main() -> Result<(), DmapError> {
//! let file = File::open("tests/test_files/test.rawacf.bz2")?;  // `File` implements the `Read` trait
//! let rawacf_data = RawacfRecord::read_records(file)?;
//!
//! let uncompressed_data = RawacfRecord::read_file("tests/test_files/test.rawacf")?;
//! assert_eq!(rawacf_data.len(), uncompressed_data.len());
//! for (left, right) in izip!(rawacf_data, uncompressed_data) {
//!     assert_eq!(left, right)
//! }
//! #     Ok(())
//! # }
//! ```

pub(crate) mod compression;
pub(crate) mod convenience;
pub mod error;
pub mod formats;
pub(crate) mod io;
mod parser;
pub mod record;
pub mod types;

#[cfg(feature = "python")]
mod python_types;

#[cfg(feature = "python")]
mod python_bindings;

pub use crate::error::DmapError;
pub use crate::formats::dmap::DmapRecord;
pub use crate::formats::fitacf::FitacfRecord;
pub use crate::formats::grid::GridRecord;
pub use crate::formats::iqdat::IqdatRecord;
pub use crate::formats::map::MapRecord;
pub use crate::formats::rawacf::RawacfRecord;
pub use crate::formats::snd::SndRecord;
pub use crate::record::Record;
use crate::types::DmapField;
use indexmap::IndexMap;
use paste::paste;
use std::io::Read;
use std::path::Path;

/// Creates functions for reading DMAP files for the Rust API.
///
/// Generates functions for:
///
/// * `read_[name]` - reads records from a file, returning an error if parsing fails
/// * `read_[name]_lax` - reads records from a file, returning successfully parsed records and the byte offset of the first invalid record, if encountered
/// * `read_[name]_bytes` - reads records from a byte slice, returning an error if parsing fails
/// * `read_[name]_bytes_lax` - reads records from a byte slice, returning successfully parsed records and the byte offset of the first invalid record, if encountered
/// * `read_[name]_by_indices` - reads specific records from a file by index
/// * `read_[name]_by_indices_lax` - reads specific records from a file by index, returning the byte offset where corruption begins, if applicable
/// * `read_[name]_bytes_by_indices` - reads specific records from a byte slice by index
/// * `read_[name]_bytes_by_indices_lax` - reads specific records from a byte slice by index, returning the byte offset where corruption begins, if applicable
/// * `peek_[name]` - reads only the first record from a file
/// * `read_[name]_metadata` - reads only metadata fields from records in a file
/// * `read_[name]_metadata_by_indices` - reads only metadata fields from specific records in a file by index
///
/// where `[name]` is one of the supported DMAP record types.
macro_rules! read_rust {
    ($name:ident, $record:ty) => {
        paste! {
            #[doc = "Attempts to read `" $record "`s from `infile`."]
            #[doc = ""]
            #[doc = "# Errors"]
            #[doc = "if there is an issue reading from file, decompressing the input, parsing DMAP records, or interpreting records as `" $record "`s."]
            pub fn [< read_ $name >]<P: AsRef<Path>>(infile: P) -> Result<Vec<$record>, DmapError> {
                <$record>::read_file(infile)
            }

            #[doc = "Attempts to read `" $record "`s from `infile` in lax mode."]
            #[doc = ""]
            #[doc = "Returns the successfully parsed records and the byte offset of the first invalid record, if one is encountered."]
            #[doc = ""]
            #[doc = "# Errors"]
            #[doc = "if there is an issue opening or reading the file."]
            pub fn [< read_ $name _lax>]<P: AsRef<Path>>(infile: P) -> Result<(Vec<$record>, Option<usize>), DmapError> {
                <$record>::read_file_lax(infile)
            }

            #[doc = "Attempts to read `" $record "`s from a byte slice."]
            #[doc = ""]
            #[doc = "# Errors"]
            #[doc = "if the bytes cannot be parsed as DMAP records or interpreted as `" $record "`s."]
            pub fn [< read_ $name _bytes >](bytes: &[u8]) -> Result<Vec<$record>, DmapError> {
                <$record>::read_records(bytes)
            }

            #[doc = "Attempts to read `" $record "`s from a byte slice in lax mode."]
            #[doc = ""]
            #[doc = "Returns the successfully parsed records and the byte offset of the first invalid record, if one is encountered."]
            #[doc = ""]
            #[doc = "# Errors"]
            #[doc = "if there is an issue parsing the provided bytes."]
            pub fn [< read_ $name _bytes_lax >](bytes: &[u8]) -> Result<(Vec<$record>, Option<usize>), DmapError> {
                <$record>::read_records_lax(bytes)
            }

            #[doc = "Attempts to read specific `" $record "` records from `infile` by index."]
            #[doc = ""]
            #[doc = "# Errors"]
            #[doc = "Returns an error if the file cannot be read, DMAP records cannot be parsed, or records cannot be interpreted as `" $record "` values."]
            pub fn [< read_ $name _by_indices >]<P: AsRef<Path>>(infile: P, indices: &[i32]) -> Result<Vec<$record>, DmapError> {
                <$record>::read_file_by_indices(infile, indices)
            }

            #[doc = "Attempts to read specific `" $record "` records from `infile` by index in lax mode."]
            #[doc = ""]
            #[doc = "Returns successfully parsed records and the byte offset of the first invalid record, if one is encountered."]
            #[doc = ""]
            #[doc = "# Errors"]
            #[doc = "Returns an error if the file cannot be opened or read."]
            pub fn [< read_ $name _by_indices_lax >]<P: AsRef<Path>>(infile: P, indices: &[i32]) -> Result<(Vec<$record>, Option<usize>), DmapError> {
                <$record>::read_file_by_indices_lax(infile, indices)
            }

            #[doc = "Attempts to read specific `" $record "` records from a DMAP data source by index."]
            #[doc = ""]
            #[doc = "# Errors"]
            #[doc = "Returns an error if DMAP records cannot be parsed or interpreted as `" $record "` values."]
            pub fn [< read_ $name _bytes_by_indices >](dmap_data: impl Read, indices: &[i32]) -> Result<Vec<$record>, DmapError> {
                <$record>::read_nth_records(dmap_data, indices)
            }

            #[doc = "Attempts to read specific `" $record "` records from a DMAP data source by index in lax mode."]
            #[doc = ""]
            #[doc = "Returns successfully parsed records and the byte offset of the first invalid record, if one is encountered."]
            #[doc = ""]
            #[doc = "# Errors"]
            #[doc = "Returns an error if the input cannot be read."]
            pub fn [< read_ $name _bytes_by_indices_lax >](dmap_data: impl Read, indices: &[i32]) -> Result<(Vec<$record>, Option<usize>), DmapError> {
                <$record>::read_nth_records_lax(dmap_data, indices)
            }

            #[doc = "Attempts to read metadata fields from `" $record "` records in `infile`."]
            #[doc = ""]
            #[doc = "# Errors"]
            #[doc = "if there is an issue reading from file or parsing DMAP records."]
            pub fn [< read_ $name _metadata >]<P: AsRef<Path>>(infile: P) -> Result<Vec<IndexMap<String, DmapField>>, DmapError> {
                <$record>::read_file_metadata(infile)
            }

            #[doc = "Attempts to read metadata fields from specific `" $record "` records in `infile` by index."]
            #[doc = ""]
            #[doc = "# Errors"]
            #[doc = "if there is an issue reading from file or parsing DMAP records."]
            pub fn [< read_ $name _metadata_by_indices >]<P: AsRef<Path>>(infile: P, indices: &[i32]) -> Result<Vec<IndexMap<String, DmapField>>, DmapError> {
                <$record>::read_file_metadata_by_indices(infile, indices)
            }
        }
    };
}

read_rust!(iqdat, IqdatRecord);
read_rust!(rawacf, RawacfRecord);
read_rust!(fitacf, FitacfRecord);
read_rust!(grid, GridRecord);
read_rust!(map, MapRecord);
read_rust!(snd, SndRecord);
read_rust!(dmap, DmapRecord);

/// This macro generates a function for attempting to convert `Vec<IndexMap>` to `Vec<$type>` and write it to file.
macro_rules! write_rust {
    ($type:ident) => {
        paste! {
            #[doc = "Attempts to convert `recs` to `" $type:camel Record "` then append to `outfile`."]
            #[doc = ""]
            #[doc = "# Errors"]
            #[doc = "if any of the `IndexMap`s are unable to be interpreted as a `" $type:camel Record "`, or there is an issue writing to file."]
            pub fn [< try_write_ $type >]<P: AsRef<Path>>(
                recs: Vec<IndexMap<String, DmapField>>,
                outfile: P,
                bz2: bool,
            ) -> Result<(), DmapError> {
                let bytes = [< $type:camel Record >]::try_into_bytes(recs)?;
                crate::io::bytes_to_file(bytes, outfile, bz2).map_err(DmapError::from)
            }
        }
    }
}

write_rust!(iqdat);
write_rust!(rawacf);
write_rust!(fitacf);
write_rust!(grid);
write_rust!(map);
write_rust!(snd);
write_rust!(dmap);
